import { Client } from 'pg';
import * as fs from 'fs';

const client = new Client({
  connectionString: process.env.PG,
});

async function generateTypes() {
  await client.connect();

  // Получаем таблицы
  const tablesResult = await client.query(`
    SELECT table_name 
    FROM information_schema.tables 
    WHERE table_schema = 'public' 
    AND table_type = 'BASE TABLE'
    ORDER BY table_name
  `);

  // Получаем колонки для каждой таблицы
  const columnsResult = await client.query(`
    SELECT table_name, column_name, data_type, is_nullable, column_default
    FROM information_schema.columns
    WHERE table_schema = 'public'
    ORDER BY table_name, ordinal_position
  `);

  // Получаем функции
  const functionsResult = await client.query(`
    SELECT routine_name, routine_type
    FROM information_schema.routines
    WHERE routine_schema = 'public'
    AND routine_type = 'FUNCTION'
    ORDER BY routine_name
  `);

  // Генерируем TypeScript типы
  let output = `// Generated by generate-types.ts\n// Do not edit manually\n\nexport namespace Database {\n  export namespace Tables {\n`;

  // Группируем колонки по таблицам
  const tablesMap = new Map<string, any[]>();
  for (const row of columnsResult.rows) {
    if (!tablesMap.has(row.table_name)) {
      tablesMap.set(row.table_name, []);
    }
    tablesMap.get(row.table_name)!.push(row);
  }

  for (const table of tablesResult.rows) {
    const columns = tablesMap.get(table.table_name) || [];
    output += `    export interface ${table.table_name} {\n`;
    for (const col of columns) {
      const tsType = mapPostgresType(col.data_type);
      const optional = col.is_nullable === 'YES' ? '?' : '';
      output += `      ${col.column_name}${optional}: ${tsType};\n`;
    }
    output += `    }\n\n`;
  }

  output += `  }\n\n  export namespace Functions {\n`;
  for (const func of functionsResult.rows) {
    output += `    ${func.routine_name}: {\n      Args: Record<string, unknown>;\n      Returns: unknown;\n    };\n`;
  }
  output += `  }\n}\n`;

  fs.writeFileSync('src/types/database.types.ts', output, 'utf-8');
  console.log('Types generated successfully!');

  await client.end();
}

function mapPostgresType(pgType: string): string {
  const typeMap: Record<string, string> = {
    'integer': 'number',
    'bigint': 'number',
    'smallint': 'number',
    'real': 'number',
    'double precision': 'number',
    'numeric': 'number',
    'boolean': 'boolean',
    'text': 'string',
    'character varying': 'string',
    'varchar': 'string',
    'char': 'string',
    'date': 'string',
    'timestamp': 'string',
    'timestamp with time zone': 'string',
    'timestamp without time zone': 'string',
    'json': 'any',
    'jsonb': 'any',
    'uuid': 'string',
  };
  return typeMap[pgType] || 'any';
}

generateTypes().catch(console.error);